<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wordle Game</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="../css/estilos.css">
  <link rel="stylesheet" href="../css/wordle.css">
</head>
<body>
<?php require_once 'header.html'?>
<div class="container">
  <h1>Wordle Game</h1>
  <div id="board">
    <!-- Rows will be generated by JavaScript -->
  </div>
  <p id="message"></p>
</div>

<script src="../js/wordle.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
